# Generated by Django 4.0.5 on 2022-06-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reactionaliases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelseedid', models.CharField(default='', max_length=16)),
                ('externalid', models.CharField(default='', max_length=64)),
                ('source', models.CharField(default='', max_length=64)),
                ('comments', models.CharField(default='', max_length=256)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reaction_aliases',
                'managed': True,
            },
        ),
    ]
