# Generated by Django 4.0.6 on 2022-07-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compoundid', models.CharField(max_length=16, unique=True)),
                ('abbreviation', models.TextField()),
                ('name', models.TextField()),
                ('formula', models.CharField(max_length=64)),
                ('mass', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('inchikey', models.CharField(max_length=64)),
                ('charge', models.CharField(max_length=16)),
                ('is_core', models.CharField(max_length=16)),
                ('is_obsolete', models.CharField(max_length=16)),
                ('linked_compound', models.CharField(max_length=64)),
                ('is_cofactor', models.CharField(max_length=16)),
                ('deltag', models.CharField(max_length=16)),
                ('deltagerr', models.CharField(max_length=16)),
                ('pka', models.CharField(max_length=256)),
                ('pkb', models.CharField(max_length=256)),
                ('abstract_compound', models.CharField(max_length=16)),
                ('comprised_of', models.CharField(max_length=16)),
                ('aliases', models.TextField()),
                ('smiles', models.TextField()),
                ('notes', models.CharField(max_length=16)),
                ('comments', models.CharField(max_length=256)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'compounds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompoundsReactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('form', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=8, null=True)),
                ('stoichiometry', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.IntegerField()),
            ],
            options={
                'db_table': 'compounds_reactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactionid', models.CharField(max_length=16)),
                ('abbreviation', models.TextField()),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('stoichiometry', models.TextField()),
                ('is_transport', models.CharField(max_length=16)),
                ('equation', models.TextField()),
                ('definition', models.TextField()),
                ('reversibility', models.CharField(max_length=16)),
                ('direction', models.CharField(max_length=16)),
                ('abstract_reaction', models.CharField(max_length=16)),
                ('pathways', models.TextField()),
                ('aliases', models.TextField()),
                ('ec_numbers', models.TextField()),
                ('deltag', models.CharField(max_length=16)),
                ('deltagerr', models.CharField(max_length=16)),
                ('compound_ids', models.TextField()),
                ('status', models.CharField(max_length=256)),
                ('is_obsolete', models.CharField(max_length=16)),
                ('linked_reaction', models.CharField(max_length=256)),
                ('notes', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=64)),
                ('comments', models.CharField(max_length=256)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'reactions',
                'managed': False,
            },
        ),
    ]
