# Generated by Django 4.0.5 on 2022-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compoundaliases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelseedid', models.CharField(max_length=16, null=True)),
                ('externalid', models.CharField(max_length=256, null=True)),
                ('source', models.CharField(max_length=64, null=True)),
                ('comments', models.CharField(max_length=256, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'compoundaliases',
                'managed': False,
            },
        ),
    ]
